name: GitEvents ICS
description: 'Tech Events meet Issue Ops'
branding:
  color: yellow
  icon: users
inputs:
  repo-token:
    description: GITHUB_TOKEN
    required: true
  default-timezone:
    description:
      'Default Timezone ID
      (https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.19)'
    default: 'Europe/Athens'
    required: true
  locations:
    description: 'JSON file with location/geo mapping'
    required: false
runs:
  main: dist/index.js
  using: node20
